### PR TITLE
PlatformIO support

### PR DESCRIPTION
**Pull request by mairas**
This PR adds support for PlatformIO, a Visual Studio Code based embedded development platform. PlatformIO provides automatic dependency handling and overall nicer development environment.

To maintain support for both Arduino IDE and PlatformIO, I had to tweak the directory layout a bit. Previous `src` subdirectory has been renamed to `SigkSens` and all remaining source files are moved under it. Additional changes include bugfixes for sending files from the program memory over HTTP.

Getting started with PlatformIO is simple. PlatformIO can be installed by following the instructions on this page: https://platformio.org/install/ide?install=vscode . Once that is done, it should be sufficient to open the project directory in VS Code and then click the PlatformIO upload button on the bottom bar.

### CODE REVIEW

**Comment by ba58smith** [comment]
If I keep using the Arduino IDE (which I almost certainly will - I like to tinker, but not enough to learn a new tool at this point), will all my code now be in /SigkSens/SigkSens? What about SigkSens.ino? It has to be in a directory called SigkSens for the Arduino IDE, but is that the top level SigkSens, or the new one you've just added below that? 

More to the point (for me), how will this change the installation instructions I've written?

**Comment by mairas** [comment]
@ba58smith the PR moves the `.ino` file under the `SigkSens/SigkSens` directory, so Arduino IDE will continue to work. After pulling the changes, you might have to re-open the project in the new location, but that should be enough. Also, all new code should go under the new hierarchy. It should be quite obvious as that's the place where all existing code resides as well.

I realize it might be frustrating but I'd modify the installation instructions to use PlatformIO instead because it just makes it so much simpler. No manual juggling with the ESP8266 build tools, dependencies or any of that. Once you have installed VSCode and PlatformIO on top of that, you clone the project, open the directory in VSCode and click the upload button. PIO automatically installs the ESP8266 target and the dependencies defined in the project.

Could you e.g. make a PR for the instructions? I could also do the modifications then.

**Comment by ba58smith** [comment]
@mairas I've been away from my computer for 4 days (unexpected trip to the US for a funeral - ugh), but now I'm back on the boat, and eager to get back into this again. If you don't mind, I'll install PlatformIO (you recommend VSCode, rather than Atom?), then go through the install process from what you've told me so far, and write up the instructions as I go. It sounds like it is a lot easier with PlatformIO - my only concern (as if I have any right to have a concern about this project, given my teeny tiny contribution to it!) is that some people - maybe a decent percentage? - who come across SigkSens might do so from an Arduino background, and not be so willing to install and learn a whole new dev tool just to try SigkSens. So for the time being, I think I'll make the the instructions cover both Arduino IDE and PlatformIO. If, in the future, it becomes too great a challenge to keep SigkSens working with both, then I can easily change the instructions to say that you have to use Platform IO.
Thoughts?

**Comment by mairas** [comment]
My condolences! :-(

No thoughts. :-D I think your plan is perfect!

**Comment by mxtommy** [comment]
Thanks :) Moving the files into a subfolder called SigKSens seems to be a best practice anyways.. (see https://github.com/mxtommy/SigkSens/pull/29 ) :)

**Pull request merged**
